apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas : 2
  strategy : RollingUpdate
  rollingUpdate :
    maxUnavailable : 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
  spec:
    containers :
      name : mycontainer
      image : image:v1
      port :
        containerPort : 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
        
